# Nome da pipeline exibindo qual gatilho acionou a execução
name: Pipelina de testes do Ecommerce
run-name: ${{ github.event_name }}

on:
  # Gatilho 1: Push na branch main
  push:
    branches: [ main ]

  # Gatilho 2: Execução agendada - toda sexta-feira às 18h (15h UTC)
  schedule:
    - cron: '0 15 * * 5'
jobs:
  run-cypress-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código-fonte
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      # Configuração do Node.js
      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # Instalação das dependências do projeto
      - name: 📦 Install dependencies
        run: npm ci

      # Execução dos testes automatizados com Cypress
      - name: 🚀 Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          config-file: cypress.config.js
          browser: ${{ github.event.inputs.browser || 'chrome' }}  # Usa o navegador informado ou 'chrome' como fallback
          headless: true
