# .github/workflows/cypress-tests.yml
name: Cypress Tests

on:
  schedule:
    - cron: '0 18 * * 5'  # Toda sexta-feira às 18h UTC
  workflow_dispatch:
    inputs:
      browser:
        description: 'Selecione o navegador para rodar os testes'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - electron
          - firefox

jobs:
  run-cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar e rodar Cypress
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ github.event.inputs.browser || 'chrome' }}
          install: true
